/**
 * Something to read while the complaints browser fills its cache.
 *
 * That first fetch was measured at 2.3-74.3s, and a spinner held for a minute
 * reads as a hang. Hardcoded rather than fetched: this is the one screen whose
 * whole job is to cover for variable latency, so putting a network call inside
 * it would add a second thing that can fail to the thing meant to smooth over
 * the first. No API is worth that here, and none offers NYC facts reliably.
 *
 * Kept to one line each so the swap never reflows the dialog.
 */
export const NYC_FACTS: readonly string[] = [
  "The city runs on 6,000 miles of streets — enough to drive from New York to Rome and back.",
  "Manhattan's street grid was laid out in 1811, sixty years before most of it was built on.",
  "The 311 service line has taken more than 500 million requests since it opened in 2003.",
  "There are more than 8 million people in New York City, speaking upwards of 700 languages.",
  "Central Park is entirely artificial — every hill, lake, and meadow was designed and built.",
  "The subway has 472 stations, more than any other system on Earth.",
  "Brooklyn would be the fourth-largest city in the United States if it stood alone.",
  "The Bronx is the only borough attached to the American mainland.",
  "Staten Island's ferry has been free since 1997 and carries 70,000 people a day.",
  "Queens is the most linguistically diverse place in the world.",
  "The Empire State Building has its own zip code: 10118.",
  "There are roughly 6,000 miles of sewer pipe beneath the streets.",
  "New York's drinking water travels up to 125 miles from the Catskills, mostly by gravity.",
  "The Brooklyn Bridge was the world's longest suspension bridge when it opened in 1883.",
  "Grand Central has 44 platforms — more than any other railway station anywhere.",
  "The city has about 666,000 street trees, each one individually mapped.",
  "Times Square is named for The New York Times, which moved there in 1904.",
  "The Statue of Liberty's copper skin is only 2.4mm thick — about two pennies.",
  "Manhattan is called that after the Lenape word 'Manna-hata', meaning hilly island.",
  "There are 1,700 parks, playgrounds and recreation facilities across the five boroughs.",
  "The first pizzeria in the United States opened on Spring Street in 1905.",
  "Wall Street is named for an actual wall, built by the Dutch in 1653.",
  "The city's bedrock is why Midtown and Downtown have skyscrapers and the space between does not.",
  "New York was the U.S. capital from 1785 to 1790.",
  "The oldest building in the city is the Wyckoff House in Brooklyn, from around 1652.",
  "Roughly 800 languages are spoken in Queens alone.",
  "The High Line was a freight railway that ran until 1980 and reopened as a park in 2009.",
  "There are more Chinese residents in New York City than in any city outside Asia.",
  "Coney Island's Cyclone has been running since 1927.",
  "The city produces about 14 million tons of waste every year.",
  "Roosevelt Island was once called Blackwell's Island, then Welfare Island.",
  "The Flatiron Building is only 6.5 feet wide at its narrowest point.",
  "Broadway follows an old Lenape trail that predates the street grid entirely.",
  "The subway's oldest section opened in 1904 and is still in daily service.",
  "There are 21 miles of beaches within the city limits.",
  "The New York Public Library's collection runs to more than 50 million items.",
  "Yellow cabs are yellow because a 1907 study found it the easiest color to spot at distance.",
  "The Chrysler Building held the world's-tallest title for eleven months.",
  "More than a third of New Yorkers were born outside the United States.",
  "Prospect Park was designed by the same pair who designed Central Park, and they preferred it.",
  "The city has more than 26,000 restaurants.",
  "Ellis Island processed roughly 12 million immigrants between 1892 and 1954.",
  "Rikers Island grew from 90 acres to more than 400 through landfill.",
  "The Staten Island Ferry crosses New York Harbor 5 miles each way.",
  "Manhattan's population swells by roughly 1.6 million people on a weekday.",
  "The Guggenheim's spiral was designed so visitors take the lift up and walk down.",
  "Newtown Creek, between Brooklyn and Queens, was the site of a bigger oil spill than the Exxon Valdez.",
  "The city's last farm, in Queens, still operates as a working museum.",
  "The Waldorf-Astoria has a private railway platform beneath it, Track 61.",
  "There are about 13,500 licensed yellow taxis.",
  "The Bronx Zoo is the largest urban zoo in the United States.",
  "Green-Wood Cemetery in Brooklyn was a tourist attraction before Central Park existed.",
  "The Verrazzano-Narrows Bridge towers are 1.625 inches farther apart at the top than the bottom, for the Earth's curvature.",
  "The city has 90 miles of protected bike lanes and counting.",
  "The Cloisters was assembled from parts of five French monasteries.",
  "New York's first subway was a secret pneumatic tube built under Broadway in 1870.",
  "There are more than 1,100 pizzerias in the five boroughs.",
  "The Chelsea Hotel has housed Dylan Thomas, Patti Smith, and Arthur C. Clarke.",
  "Fifth Avenue splits the East and West sides of Manhattan's address system.",
  "About 1.1 million students attend New York City public schools.",
  "The Unisphere in Queens was built for the 1964 World's Fair and still stands.",
  "Hart Island holds more than a million burials and is the largest public cemetery in the U.S.",
  "The Manhattan Bridge's walkway offers the best view of the Brooklyn Bridge.",
  "New York City has its own official soil type, called Ebbets.",
  "Astoria was named after John Jacob Astor, who visited once.",
  "The Little Red Lighthouse under the George Washington Bridge was saved by a children's book.",
  "There are more than 700 miles of subway track.",
  "The first American chess tournament was held in New York in 1857.",
  "Governors Island was a military base for nearly 200 years before opening to the public.",
  "The Woolworth Building was called the Cathedral of Commerce when it opened in 1913.",
  "New York has more bridges than Venice — 789 of them.",
  "The oldest continuously operating bar in the city is McSorley's, from 1854.",
  "Brooklyn Bridge Park was built on decommissioned shipping piers.",
  "The city's tap water is tested about 500,000 times a year.",
  "Riverside Park was built to cover the New York Central railway tracks.",
  "The Dakota was so far uptown when built that people joked it might as well be in Dakota.",
  "The Bowery is the oldest thoroughfare on Manhattan Island.",
  "New York's Chinatown is the largest concentration of Chinese people in the Western Hemisphere.",
  "The Empire State Building was finished ahead of schedule and under budget in 1931.",
  "There are roughly 300 miles of shoreline in New York City — more than Miami, Boston and LA combined.",
  "The Queensboro Bridge appears in more films than almost any other city landmark.",
  "Washington Square Park was a burial ground before it was a park; some 20,000 people rest beneath it.",
  "The city has 11,000 acres of parkland in the Bronx alone.",
  "Katz's Delicatessen has been on Houston Street since 1888.",
  "The subway once used tokens; they were retired in 2003.",
  "New York's first pizza slice sold for five cents.",
  "The Staten Island Greenbelt is nearly three times the size of Central Park.",
  "Steinway & Sons has built pianos in Queens since 1870.",
  "The Bronx River is the only true freshwater river in the city.",
  "The Apollo Theater's amateur night has run since 1934.",
  "There are over 500 art galleries in Manhattan.",
  "Roosevelt Avenue in Queens runs beneath the 7 train for more than five miles.",
  "The Public Theater staged the first Shakespeare in the Park in 1962.",
  "New York City's water supply serves nearly half of New York State's population.",
  "Coney Island hosted the first American roller coaster in 1884.",
  "The city's street signs changed from all-caps to mixed case for legibility.",
  "Jamaica Bay is a national park and a major bird migration stop.",
  "The Cyclone, Wonder Wheel and Parachute Jump are all official city landmarks.",
  "There are more than 1,000 community gardens across the five boroughs.",
  "The Holland Tunnel was the first mechanically ventilated underwater tunnel in the world.",
];
